import './globals.css'
import 'antd/dist/antd.css'
import type { Metadata } from 'next'
import Navbar from '@/src/app/components/Navbar';
import { Providers } from './providers';
import Footer from '@/src/app/components/Footer';
 
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="dark:bg-[#1f2028] bg-white antialiased min-h-screen flex flex-col">
        <Providers>
          <Navbar />


          <div className="flex min-h-screen flex-col justify-between">
          <main className="relative flex-auto min-w-0 md:mt-0 flex flex-col justify-center" style={{ scrollPaddingTop: '150px' }}>
            {children}
          </main>
          <Footer />
        </div>
  
        </Providers>
      </body>
    </html>
  );
}
